name: Publish Release

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        name: Checkout sources

      - uses: actions/setup-java@v4
        name: Set up JDK 11
        with:
          java-version: '11'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4
        name: Setup Gradle

      - name: Publish Artifact
        if: github.repository == 'Adrigamer2950/Base36'
        env:
          NEXUS_USERNAME: "${{ secrets.NEXUS_USERNAME }}"
          NEXUS_PASSWORD: "${{ secrets.NEXUS_PASSWORD }}"
        run: "chmod +x ./gradlew && ./gradlew publishMavenPublicationToMavenRepository -PNEXUS_USERNAME=$NEXUS_USERNAME -PNEXUS_PASSWORD=$NEXUS_PASSWORD"
